import { Component } from '@angular/core';
import { setLicenseKey } from '@grapecity/wijmo';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'privelage';

  constructor() {
    // set wijmo license key
    setLicenseKey('fcc.zignexlogistics.com|fcc.zignexlogestics.com|demo.zignexlogistics.com|www.zignexlogistics.com|localhost|qa.zignexlogistics.com,531633231395724#B0ILcQjM7UTOzEzMyMzM6EzM5IiOiQWSiwSfdtlOicGbmJCLiMjdxIDMyIiOiIXZ6JCLlNHbhZmOiI7ckJye0ICbuFkI1pjIEJCLi4TPnNHMVFTdwdTVNVWVaNWeqBlbtZGRF3CV6UFWFdDZSlTSVdDVUd4V8p5d4R4N5oHd6h5c45UYURkRxQmcIx6KaRXcrI5SLJje5RFVzZXUHJDOSRVTH3kYwEzUOB5KQtGZlpXQHJ6bvkmSz4WRnhTOadzbU3UZLNnQFtWNlJmRvhGN8MDMiBDTXx6S7MVYF3UQPl7cGp5Knh6Z6E4YxFVYCNnSCR6btdmYSBXYXh6YJFjMBtUWRZXVw2EWwknNJh5R6ZTR9QmTPJnZINEZnFle4N5b6hkS9Bzd9VVO0l7cRFkUTdDbONWeRBHOkJTcNpWQrl5NoFUZCt4Q626QwBlV9R5S4YlZONGNxJUe8VGW7dkewF7KyIXa8F7Sy3WdwFjbtNWOvsmN0VzZwVmUTBVNMZWZzMXZIJFaO9UdGV7aZ3WWPF7ZSVHcuR7KNtkcYRESZx6UXtyYiojITJCLiAzNBVDOzYkI0ICSiwiN5QDN5EjN6gTM0IicfJye#4Xfd5nIJBjMSJiOiMkIsIibvl6cuVGd8VEIgQXZlh6U8VGbGBybtpWaXJiOi8kI1xSfiUTSOFlI0IyQiwiIu3Waz9WZ4hXRgAicldXZpZFdy3GclJFIv5mapdlI0IiTisHL3JyS7gDSiojIDJCLi86bpNnblRHeFBCI73mUpRHb55EIv5mapdlI0IiTisHL3JCNGZDRiojIDJCLi86bpNnblRHeFBCIQFETPBCIv5mapdlI0IiTisHL3JyMDBjQiojIDJCLiUmcvNEIv5mapdlI0IiTisHL3JSV8cTQiojIDJCLi86bpNnblRHeFBCI4JXYoNEbhl6YuFmbpZEIv5mapdlI0IiTis7W0ICZyBlIsIyMyMzM9ADIwITOwIjMwIjI0ICdyNkIsISbvNmLzNWa4NXan3Gb8VmbnlmeuEWcsQ7cvhGbhN6bsxSbvNmLzNWa4NXan3Gb8Vmbnlmeuc7d7xSbvNmLzNWa4NXan3Gb8Vmbnlmeu2WblRGLt36YuM7YpR7cld6bshXZudWa09yYjZGLt36YuM7YpR7cpd6bshXZudWa09yYjZmI0IyctRkIsIyYulEIsgXRudWaaJiOiEdTMJ');
  }

}
